// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: aki.proto

package akikit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AkiService_OpenSession_FullMethodName               = "/akiservice.AkiService/OpenSession"
	AkiService_CloseSession_FullMethodName              = "/akiservice.AkiService/CloseSession"
	AkiService_Ping_FullMethodName                      = "/akiservice.AkiService/Ping"
	AkiService_Hubs_FullMethodName                      = "/akiservice.AkiService/Hubs"
	AkiService_Anisette_FullMethodName                  = "/akiservice.AkiService/Anisette"
	AkiService_AnisetteProvisionStart_FullMethodName    = "/akiservice.AkiService/AnisetteProvisionStart"
	AkiService_AnisetteProvisionEnd_FullMethodName      = "/akiservice.AkiService/AnisetteProvisionEnd"
	AkiService_AnisetteIsProvisioned_FullMethodName     = "/akiservice.AkiService/AnisetteIsProvisioned"
	AkiService_AnisetteProvisionErase_FullMethodName    = "/akiservice.AkiService/AnisetteProvisionErase"
	AkiService_SetRoutingInfo_FullMethodName            = "/akiservice.AkiService/SetRoutingInfo"
	AkiService_GetRoutingInfo_FullMethodName            = "/akiservice.AkiService/GetRoutingInfo"
	AkiService_AnisetteSynchronize_FullMethodName       = "/akiservice.AkiService/AnisetteSynchronize"
	AkiService_LoginCode_FullMethodName                 = "/akiservice.AkiService/LoginCode"
	AkiService_SAPExchange_FullMethodName               = "/akiservice.AkiService/SAPExchange"
	AkiService_SAPSign_FullMethodName                   = "/akiservice.AkiService/SAPSign"
	AkiService_SAPPrimeSign_FullMethodName              = "/akiservice.AkiService/SAPPrimeSign"
	AkiService_SAPVerify_FullMethodName                 = "/akiservice.AkiService/SAPVerify"
	AkiService_SAPPrimeVerify_FullMethodName            = "/akiservice.AkiService/SAPPrimeVerify"
	AkiService_CloseSAPContext_FullMethodName           = "/akiservice.AkiService/CloseSAPContext"
	AkiService_SSVGetFairPlayContext_FullMethodName     = "/akiservice.AkiService/SSVGetFairPlayContext"
	AkiService_SSVIsValidContext_FullMethodName         = "/akiservice.AkiService/SSVIsValidContext"
	AkiService_SSVSubscriptionBag_FullMethodName        = "/akiservice.AkiService/SSVSubscriptionBag"
	AkiService_SSVSubscriptionRequest_FullMethodName    = "/akiservice.AkiService/SSVSubscriptionRequest"
	AkiService_SSVImportKeybag_FullMethodName           = "/akiservice.AkiService/SSVImportKeybag"
	AkiService_SSVImportSubKeybag_FullMethodName        = "/akiservice.AkiService/SSVImportSubKeybag"
	AkiService_SSVImportSubResponse_FullMethodName      = "/akiservice.AkiService/SSVImportSubResponse"
	AkiService_SSVStopSubscriptionLease_FullMethodName  = "/akiservice.AkiService/SSVStopSubscriptionLease"
	AkiService_SSVDestroyFairPlayContext_FullMethodName = "/akiservice.AkiService/SSVDestroyFairPlayContext"
	AkiService_SSVKeyBagSyncData_FullMethodName         = "/akiservice.AkiService/SSVKeyBagSyncData"
	AkiService_QuickSign_FullMethodName                 = "/akiservice.AkiService/QuickSign"
	AkiService_RSASign_FullMethodName                   = "/akiservice.AkiService/RSASign"
	AkiService_NACExchange1_FullMethodName              = "/akiservice.AkiService/NACExchange1"
	AkiService_NACExchange2_FullMethodName              = "/akiservice.AkiService/NACExchange2"
	AkiService_NACSign_FullMethodName                   = "/akiservice.AkiService/NACSign"
	AkiService_CloseNACContext_FullMethodName           = "/akiservice.AkiService/CloseNACContext"
)

// AkiServiceClient is the client API for AkiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AkiServiceClient interface {
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*Session, error)
	CloseSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Empty, error)
	Ping(ctx context.Context, in *Session, opts ...grpc.CallOption) (*PingReply, error)
	Hubs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HubsReply, error)
	Anisette(ctx context.Context, in *AnisetteRequest, opts ...grpc.CallOption) (*AnisetteReply, error)
	AnisetteProvisionStart(ctx context.Context, in *AnisetteProvisionStartRequest, opts ...grpc.CallOption) (*AnisetteProvisionStartReply, error)
	AnisetteProvisionEnd(ctx context.Context, in *AnisetteProvisionEndRequest, opts ...grpc.CallOption) (*AnisetteProvisionEndReply, error)
	AnisetteIsProvisioned(ctx context.Context, in *AnisetteRequest, opts ...grpc.CallOption) (*AnisetteStatusReply, error)
	AnisetteProvisionErase(ctx context.Context, in *AnisetteRequest, opts ...grpc.CallOption) (*AnisetteStatusReply, error)
	SetRoutingInfo(ctx context.Context, in *SetRoutingInfoRequest, opts ...grpc.CallOption) (*AnisetteProvisionEndReply, error)
	GetRoutingInfo(ctx context.Context, in *GetRoutingInfoRequest, opts ...grpc.CallOption) (*GetRoutingInfoReply, error)
	AnisetteSynchronize(ctx context.Context, in *AnisetteSynchronizeRequest, opts ...grpc.CallOption) (*AnisetteSynchronizeReply, error)
	LoginCode(ctx context.Context, in *LoginCodeRequest, opts ...grpc.CallOption) (*LoginCodeReply, error)
	SAPExchange(ctx context.Context, in *SAPExchangeRequest, opts ...grpc.CallOption) (*SAPExchangeReply, error)
	SAPSign(ctx context.Context, in *SAPSignRequest, opts ...grpc.CallOption) (*SAPSignReply, error)
	SAPPrimeSign(ctx context.Context, in *SAPSignRequest, opts ...grpc.CallOption) (*SAPSignReply, error)
	SAPVerify(ctx context.Context, in *SAPVerifyRequest, opts ...grpc.CallOption) (*SAPVerifyReply, error)
	SAPPrimeVerify(ctx context.Context, in *SAPVerifyRequest, opts ...grpc.CallOption) (*SAPVerifyReply, error)
	CloseSAPContext(ctx context.Context, in *CtxHandle, opts ...grpc.CallOption) (*Empty, error)
	SSVGetFairPlayContext(ctx context.Context, in *SSVGetContextRequest, opts ...grpc.CallOption) (*SSVGetContextReply, error)
	SSVIsValidContext(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*SSVIsValidContextReply, error)
	SSVSubscriptionBag(ctx context.Context, in *SSVSubBagRequest, opts ...grpc.CallOption) (*SSVSubBagReply, error)
	SSVSubscriptionRequest(ctx context.Context, in *SSVSubscriptionRequestRequest, opts ...grpc.CallOption) (*SSVSubscriptionRequestReply, error)
	SSVImportKeybag(ctx context.Context, in *SSVImportKeybagRequest, opts ...grpc.CallOption) (*SSVImportReply, error)
	SSVImportSubKeybag(ctx context.Context, in *SSVImportKeybagRequest, opts ...grpc.CallOption) (*SSVImportReply, error)
	SSVImportSubResponse(ctx context.Context, in *SSVImportSubResponseRequest, opts ...grpc.CallOption) (*SSVImportReply, error)
	SSVStopSubscriptionLease(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*Empty, error)
	SSVDestroyFairPlayContext(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*Empty, error)
	SSVKeyBagSyncData(ctx context.Context, in *SSVKeyBagSyncDataRequest, opts ...grpc.CallOption) (*SSVKeyBagSyncDataReply, error)
	QuickSign(ctx context.Context, in *QuickSignRequest, opts ...grpc.CallOption) (*QuickSignReply, error)
	RSASign(ctx context.Context, in *RSASignRequest, opts ...grpc.CallOption) (*RSASignReply, error)
	NACExchange1(ctx context.Context, in *NACExchange1Request, opts ...grpc.CallOption) (*NACExchange1Reply, error)
	NACExchange2(ctx context.Context, in *NACExchange2Request, opts ...grpc.CallOption) (*Empty, error)
	NACSign(ctx context.Context, in *NACSignRequest, opts ...grpc.CallOption) (*NACSignReply, error)
	CloseNACContext(ctx context.Context, in *CtxHandle, opts ...grpc.CallOption) (*Empty, error)
}

type akiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAkiServiceClient(cc grpc.ClientConnInterface) AkiServiceClient {
	return &akiServiceClient{cc}
}

func (c *akiServiceClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, AkiService_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) CloseSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) Ping(ctx context.Context, in *Session, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, AkiService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) Hubs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HubsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HubsReply)
	err := c.cc.Invoke(ctx, AkiService_Hubs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) Anisette(ctx context.Context, in *AnisetteRequest, opts ...grpc.CallOption) (*AnisetteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnisetteReply)
	err := c.cc.Invoke(ctx, AkiService_Anisette_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) AnisetteProvisionStart(ctx context.Context, in *AnisetteProvisionStartRequest, opts ...grpc.CallOption) (*AnisetteProvisionStartReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnisetteProvisionStartReply)
	err := c.cc.Invoke(ctx, AkiService_AnisetteProvisionStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) AnisetteProvisionEnd(ctx context.Context, in *AnisetteProvisionEndRequest, opts ...grpc.CallOption) (*AnisetteProvisionEndReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnisetteProvisionEndReply)
	err := c.cc.Invoke(ctx, AkiService_AnisetteProvisionEnd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) AnisetteIsProvisioned(ctx context.Context, in *AnisetteRequest, opts ...grpc.CallOption) (*AnisetteStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnisetteStatusReply)
	err := c.cc.Invoke(ctx, AkiService_AnisetteIsProvisioned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) AnisetteProvisionErase(ctx context.Context, in *AnisetteRequest, opts ...grpc.CallOption) (*AnisetteStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnisetteStatusReply)
	err := c.cc.Invoke(ctx, AkiService_AnisetteProvisionErase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SetRoutingInfo(ctx context.Context, in *SetRoutingInfoRequest, opts ...grpc.CallOption) (*AnisetteProvisionEndReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnisetteProvisionEndReply)
	err := c.cc.Invoke(ctx, AkiService_SetRoutingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) GetRoutingInfo(ctx context.Context, in *GetRoutingInfoRequest, opts ...grpc.CallOption) (*GetRoutingInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingInfoReply)
	err := c.cc.Invoke(ctx, AkiService_GetRoutingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) AnisetteSynchronize(ctx context.Context, in *AnisetteSynchronizeRequest, opts ...grpc.CallOption) (*AnisetteSynchronizeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnisetteSynchronizeReply)
	err := c.cc.Invoke(ctx, AkiService_AnisetteSynchronize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) LoginCode(ctx context.Context, in *LoginCodeRequest, opts ...grpc.CallOption) (*LoginCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginCodeReply)
	err := c.cc.Invoke(ctx, AkiService_LoginCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SAPExchange(ctx context.Context, in *SAPExchangeRequest, opts ...grpc.CallOption) (*SAPExchangeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SAPExchangeReply)
	err := c.cc.Invoke(ctx, AkiService_SAPExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SAPSign(ctx context.Context, in *SAPSignRequest, opts ...grpc.CallOption) (*SAPSignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SAPSignReply)
	err := c.cc.Invoke(ctx, AkiService_SAPSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SAPPrimeSign(ctx context.Context, in *SAPSignRequest, opts ...grpc.CallOption) (*SAPSignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SAPSignReply)
	err := c.cc.Invoke(ctx, AkiService_SAPPrimeSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SAPVerify(ctx context.Context, in *SAPVerifyRequest, opts ...grpc.CallOption) (*SAPVerifyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SAPVerifyReply)
	err := c.cc.Invoke(ctx, AkiService_SAPVerify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SAPPrimeVerify(ctx context.Context, in *SAPVerifyRequest, opts ...grpc.CallOption) (*SAPVerifyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SAPVerifyReply)
	err := c.cc.Invoke(ctx, AkiService_SAPPrimeVerify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) CloseSAPContext(ctx context.Context, in *CtxHandle, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_CloseSAPContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVGetFairPlayContext(ctx context.Context, in *SSVGetContextRequest, opts ...grpc.CallOption) (*SSVGetContextReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVGetContextReply)
	err := c.cc.Invoke(ctx, AkiService_SSVGetFairPlayContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVIsValidContext(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*SSVIsValidContextReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVIsValidContextReply)
	err := c.cc.Invoke(ctx, AkiService_SSVIsValidContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVSubscriptionBag(ctx context.Context, in *SSVSubBagRequest, opts ...grpc.CallOption) (*SSVSubBagReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVSubBagReply)
	err := c.cc.Invoke(ctx, AkiService_SSVSubscriptionBag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVSubscriptionRequest(ctx context.Context, in *SSVSubscriptionRequestRequest, opts ...grpc.CallOption) (*SSVSubscriptionRequestReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVSubscriptionRequestReply)
	err := c.cc.Invoke(ctx, AkiService_SSVSubscriptionRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVImportKeybag(ctx context.Context, in *SSVImportKeybagRequest, opts ...grpc.CallOption) (*SSVImportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVImportReply)
	err := c.cc.Invoke(ctx, AkiService_SSVImportKeybag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVImportSubKeybag(ctx context.Context, in *SSVImportKeybagRequest, opts ...grpc.CallOption) (*SSVImportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVImportReply)
	err := c.cc.Invoke(ctx, AkiService_SSVImportSubKeybag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVImportSubResponse(ctx context.Context, in *SSVImportSubResponseRequest, opts ...grpc.CallOption) (*SSVImportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVImportReply)
	err := c.cc.Invoke(ctx, AkiService_SSVImportSubResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVStopSubscriptionLease(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_SSVStopSubscriptionLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVDestroyFairPlayContext(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_SSVDestroyFairPlayContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVKeyBagSyncData(ctx context.Context, in *SSVKeyBagSyncDataRequest, opts ...grpc.CallOption) (*SSVKeyBagSyncDataReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVKeyBagSyncDataReply)
	err := c.cc.Invoke(ctx, AkiService_SSVKeyBagSyncData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) QuickSign(ctx context.Context, in *QuickSignRequest, opts ...grpc.CallOption) (*QuickSignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuickSignReply)
	err := c.cc.Invoke(ctx, AkiService_QuickSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) RSASign(ctx context.Context, in *RSASignRequest, opts ...grpc.CallOption) (*RSASignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RSASignReply)
	err := c.cc.Invoke(ctx, AkiService_RSASign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) NACExchange1(ctx context.Context, in *NACExchange1Request, opts ...grpc.CallOption) (*NACExchange1Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NACExchange1Reply)
	err := c.cc.Invoke(ctx, AkiService_NACExchange1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) NACExchange2(ctx context.Context, in *NACExchange2Request, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_NACExchange2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) NACSign(ctx context.Context, in *NACSignRequest, opts ...grpc.CallOption) (*NACSignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NACSignReply)
	err := c.cc.Invoke(ctx, AkiService_NACSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) CloseNACContext(ctx context.Context, in *CtxHandle, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_CloseNACContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AkiServiceServer is the server API for AkiService service.
// All implementations must embed UnimplementedAkiServiceServer
// for forward compatibility.
type AkiServiceServer interface {
	OpenSession(context.Context, *OpenSessionRequest) (*Session, error)
	CloseSession(context.Context, *Session) (*Empty, error)
	Ping(context.Context, *Session) (*PingReply, error)
	Hubs(context.Context, *Empty) (*HubsReply, error)
	Anisette(context.Context, *AnisetteRequest) (*AnisetteReply, error)
	AnisetteProvisionStart(context.Context, *AnisetteProvisionStartRequest) (*AnisetteProvisionStartReply, error)
	AnisetteProvisionEnd(context.Context, *AnisetteProvisionEndRequest) (*AnisetteProvisionEndReply, error)
	AnisetteIsProvisioned(context.Context, *AnisetteRequest) (*AnisetteStatusReply, error)
	AnisetteProvisionErase(context.Context, *AnisetteRequest) (*AnisetteStatusReply, error)
	SetRoutingInfo(context.Context, *SetRoutingInfoRequest) (*AnisetteProvisionEndReply, error)
	GetRoutingInfo(context.Context, *GetRoutingInfoRequest) (*GetRoutingInfoReply, error)
	AnisetteSynchronize(context.Context, *AnisetteSynchronizeRequest) (*AnisetteSynchronizeReply, error)
	LoginCode(context.Context, *LoginCodeRequest) (*LoginCodeReply, error)
	SAPExchange(context.Context, *SAPExchangeRequest) (*SAPExchangeReply, error)
	SAPSign(context.Context, *SAPSignRequest) (*SAPSignReply, error)
	SAPPrimeSign(context.Context, *SAPSignRequest) (*SAPSignReply, error)
	SAPVerify(context.Context, *SAPVerifyRequest) (*SAPVerifyReply, error)
	SAPPrimeVerify(context.Context, *SAPVerifyRequest) (*SAPVerifyReply, error)
	CloseSAPContext(context.Context, *CtxHandle) (*Empty, error)
	SSVGetFairPlayContext(context.Context, *SSVGetContextRequest) (*SSVGetContextReply, error)
	SSVIsValidContext(context.Context, *SSVContextHandle) (*SSVIsValidContextReply, error)
	SSVSubscriptionBag(context.Context, *SSVSubBagRequest) (*SSVSubBagReply, error)
	SSVSubscriptionRequest(context.Context, *SSVSubscriptionRequestRequest) (*SSVSubscriptionRequestReply, error)
	SSVImportKeybag(context.Context, *SSVImportKeybagRequest) (*SSVImportReply, error)
	SSVImportSubKeybag(context.Context, *SSVImportKeybagRequest) (*SSVImportReply, error)
	SSVImportSubResponse(context.Context, *SSVImportSubResponseRequest) (*SSVImportReply, error)
	SSVStopSubscriptionLease(context.Context, *SSVContextHandle) (*Empty, error)
	SSVDestroyFairPlayContext(context.Context, *SSVContextHandle) (*Empty, error)
	SSVKeyBagSyncData(context.Context, *SSVKeyBagSyncDataRequest) (*SSVKeyBagSyncDataReply, error)
	QuickSign(context.Context, *QuickSignRequest) (*QuickSignReply, error)
	RSASign(context.Context, *RSASignRequest) (*RSASignReply, error)
	NACExchange1(context.Context, *NACExchange1Request) (*NACExchange1Reply, error)
	NACExchange2(context.Context, *NACExchange2Request) (*Empty, error)
	NACSign(context.Context, *NACSignRequest) (*NACSignReply, error)
	CloseNACContext(context.Context, *CtxHandle) (*Empty, error)
	mustEmbedUnimplementedAkiServiceServer()
}

// UnimplementedAkiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAkiServiceServer struct{}

func (UnimplementedAkiServiceServer) OpenSession(context.Context, *OpenSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedAkiServiceServer) CloseSession(context.Context, *Session) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedAkiServiceServer) Ping(context.Context, *Session) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAkiServiceServer) Hubs(context.Context, *Empty) (*HubsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hubs not implemented")
}
func (UnimplementedAkiServiceServer) Anisette(context.Context, *AnisetteRequest) (*AnisetteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Anisette not implemented")
}
func (UnimplementedAkiServiceServer) AnisetteProvisionStart(context.Context, *AnisetteProvisionStartRequest) (*AnisetteProvisionStartReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnisetteProvisionStart not implemented")
}
func (UnimplementedAkiServiceServer) AnisetteProvisionEnd(context.Context, *AnisetteProvisionEndRequest) (*AnisetteProvisionEndReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnisetteProvisionEnd not implemented")
}
func (UnimplementedAkiServiceServer) AnisetteIsProvisioned(context.Context, *AnisetteRequest) (*AnisetteStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnisetteIsProvisioned not implemented")
}
func (UnimplementedAkiServiceServer) AnisetteProvisionErase(context.Context, *AnisetteRequest) (*AnisetteStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnisetteProvisionErase not implemented")
}
func (UnimplementedAkiServiceServer) SetRoutingInfo(context.Context, *SetRoutingInfoRequest) (*AnisetteProvisionEndReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRoutingInfo not implemented")
}
func (UnimplementedAkiServiceServer) GetRoutingInfo(context.Context, *GetRoutingInfoRequest) (*GetRoutingInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingInfo not implemented")
}
func (UnimplementedAkiServiceServer) AnisetteSynchronize(context.Context, *AnisetteSynchronizeRequest) (*AnisetteSynchronizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnisetteSynchronize not implemented")
}
func (UnimplementedAkiServiceServer) LoginCode(context.Context, *LoginCodeRequest) (*LoginCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginCode not implemented")
}
func (UnimplementedAkiServiceServer) SAPExchange(context.Context, *SAPExchangeRequest) (*SAPExchangeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAPExchange not implemented")
}
func (UnimplementedAkiServiceServer) SAPSign(context.Context, *SAPSignRequest) (*SAPSignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAPSign not implemented")
}
func (UnimplementedAkiServiceServer) SAPPrimeSign(context.Context, *SAPSignRequest) (*SAPSignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAPPrimeSign not implemented")
}
func (UnimplementedAkiServiceServer) SAPVerify(context.Context, *SAPVerifyRequest) (*SAPVerifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAPVerify not implemented")
}
func (UnimplementedAkiServiceServer) SAPPrimeVerify(context.Context, *SAPVerifyRequest) (*SAPVerifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAPPrimeVerify not implemented")
}
func (UnimplementedAkiServiceServer) CloseSAPContext(context.Context, *CtxHandle) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSAPContext not implemented")
}
func (UnimplementedAkiServiceServer) SSVGetFairPlayContext(context.Context, *SSVGetContextRequest) (*SSVGetContextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVGetFairPlayContext not implemented")
}
func (UnimplementedAkiServiceServer) SSVIsValidContext(context.Context, *SSVContextHandle) (*SSVIsValidContextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVIsValidContext not implemented")
}
func (UnimplementedAkiServiceServer) SSVSubscriptionBag(context.Context, *SSVSubBagRequest) (*SSVSubBagReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVSubscriptionBag not implemented")
}
func (UnimplementedAkiServiceServer) SSVSubscriptionRequest(context.Context, *SSVSubscriptionRequestRequest) (*SSVSubscriptionRequestReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVSubscriptionRequest not implemented")
}
func (UnimplementedAkiServiceServer) SSVImportKeybag(context.Context, *SSVImportKeybagRequest) (*SSVImportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVImportKeybag not implemented")
}
func (UnimplementedAkiServiceServer) SSVImportSubKeybag(context.Context, *SSVImportKeybagRequest) (*SSVImportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVImportSubKeybag not implemented")
}
func (UnimplementedAkiServiceServer) SSVImportSubResponse(context.Context, *SSVImportSubResponseRequest) (*SSVImportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVImportSubResponse not implemented")
}
func (UnimplementedAkiServiceServer) SSVStopSubscriptionLease(context.Context, *SSVContextHandle) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVStopSubscriptionLease not implemented")
}
func (UnimplementedAkiServiceServer) SSVDestroyFairPlayContext(context.Context, *SSVContextHandle) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVDestroyFairPlayContext not implemented")
}
func (UnimplementedAkiServiceServer) SSVKeyBagSyncData(context.Context, *SSVKeyBagSyncDataRequest) (*SSVKeyBagSyncDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVKeyBagSyncData not implemented")
}
func (UnimplementedAkiServiceServer) QuickSign(context.Context, *QuickSignRequest) (*QuickSignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuickSign not implemented")
}
func (UnimplementedAkiServiceServer) RSASign(context.Context, *RSASignRequest) (*RSASignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RSASign not implemented")
}
func (UnimplementedAkiServiceServer) NACExchange1(context.Context, *NACExchange1Request) (*NACExchange1Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NACExchange1 not implemented")
}
func (UnimplementedAkiServiceServer) NACExchange2(context.Context, *NACExchange2Request) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NACExchange2 not implemented")
}
func (UnimplementedAkiServiceServer) NACSign(context.Context, *NACSignRequest) (*NACSignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NACSign not implemented")
}
func (UnimplementedAkiServiceServer) CloseNACContext(context.Context, *CtxHandle) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseNACContext not implemented")
}
func (UnimplementedAkiServiceServer) mustEmbedUnimplementedAkiServiceServer() {}
func (UnimplementedAkiServiceServer) testEmbeddedByValue()                    {}

// UnsafeAkiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AkiServiceServer will
// result in compilation errors.
type UnsafeAkiServiceServer interface {
	mustEmbedUnimplementedAkiServiceServer()
}

func RegisterAkiServiceServer(s grpc.ServiceRegistrar, srv AkiServiceServer) {
	// If the following call pancis, it indicates UnimplementedAkiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AkiService_ServiceDesc, srv)
}

func _AkiService_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).CloseSession(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).Ping(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_Hubs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).Hubs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_Hubs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).Hubs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_Anisette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnisetteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).Anisette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_Anisette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).Anisette(ctx, req.(*AnisetteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_AnisetteProvisionStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnisetteProvisionStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).AnisetteProvisionStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_AnisetteProvisionStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).AnisetteProvisionStart(ctx, req.(*AnisetteProvisionStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_AnisetteProvisionEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnisetteProvisionEndRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).AnisetteProvisionEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_AnisetteProvisionEnd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).AnisetteProvisionEnd(ctx, req.(*AnisetteProvisionEndRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_AnisetteIsProvisioned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnisetteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).AnisetteIsProvisioned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_AnisetteIsProvisioned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).AnisetteIsProvisioned(ctx, req.(*AnisetteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_AnisetteProvisionErase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnisetteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).AnisetteProvisionErase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_AnisetteProvisionErase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).AnisetteProvisionErase(ctx, req.(*AnisetteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SetRoutingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoutingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SetRoutingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SetRoutingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SetRoutingInfo(ctx, req.(*SetRoutingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_GetRoutingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).GetRoutingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_GetRoutingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).GetRoutingInfo(ctx, req.(*GetRoutingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_AnisetteSynchronize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnisetteSynchronizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).AnisetteSynchronize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_AnisetteSynchronize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).AnisetteSynchronize(ctx, req.(*AnisetteSynchronizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_LoginCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).LoginCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_LoginCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).LoginCode(ctx, req.(*LoginCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SAPExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAPExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SAPExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SAPExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SAPExchange(ctx, req.(*SAPExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SAPSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAPSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SAPSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SAPSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SAPSign(ctx, req.(*SAPSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SAPPrimeSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAPSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SAPPrimeSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SAPPrimeSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SAPPrimeSign(ctx, req.(*SAPSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SAPVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAPVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SAPVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SAPVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SAPVerify(ctx, req.(*SAPVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SAPPrimeVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAPVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SAPPrimeVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SAPPrimeVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SAPPrimeVerify(ctx, req.(*SAPVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_CloseSAPContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtxHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).CloseSAPContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_CloseSAPContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).CloseSAPContext(ctx, req.(*CtxHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVGetFairPlayContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVGetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVGetFairPlayContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVGetFairPlayContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVGetFairPlayContext(ctx, req.(*SSVGetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVIsValidContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVContextHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVIsValidContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVIsValidContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVIsValidContext(ctx, req.(*SSVContextHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVSubscriptionBag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVSubBagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVSubscriptionBag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVSubscriptionBag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVSubscriptionBag(ctx, req.(*SSVSubBagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVSubscriptionRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVSubscriptionRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVSubscriptionRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVSubscriptionRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVSubscriptionRequest(ctx, req.(*SSVSubscriptionRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVImportKeybag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVImportKeybagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVImportKeybag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVImportKeybag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVImportKeybag(ctx, req.(*SSVImportKeybagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVImportSubKeybag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVImportKeybagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVImportSubKeybag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVImportSubKeybag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVImportSubKeybag(ctx, req.(*SSVImportKeybagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVImportSubResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVImportSubResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVImportSubResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVImportSubResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVImportSubResponse(ctx, req.(*SSVImportSubResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVStopSubscriptionLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVContextHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVStopSubscriptionLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVStopSubscriptionLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVStopSubscriptionLease(ctx, req.(*SSVContextHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVDestroyFairPlayContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVContextHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVDestroyFairPlayContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVDestroyFairPlayContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVDestroyFairPlayContext(ctx, req.(*SSVContextHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVKeyBagSyncData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVKeyBagSyncDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVKeyBagSyncData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVKeyBagSyncData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVKeyBagSyncData(ctx, req.(*SSVKeyBagSyncDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_QuickSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuickSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).QuickSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_QuickSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).QuickSign(ctx, req.(*QuickSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_RSASign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSASignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).RSASign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_RSASign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).RSASign(ctx, req.(*RSASignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_NACExchange1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NACExchange1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).NACExchange1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_NACExchange1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).NACExchange1(ctx, req.(*NACExchange1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_NACExchange2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NACExchange2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).NACExchange2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_NACExchange2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).NACExchange2(ctx, req.(*NACExchange2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_NACSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NACSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).NACSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_NACSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).NACSign(ctx, req.(*NACSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_CloseNACContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtxHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).CloseNACContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_CloseNACContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).CloseNACContext(ctx, req.(*CtxHandle))
	}
	return interceptor(ctx, in, info, handler)
}

// AkiService_ServiceDesc is the grpc.ServiceDesc for AkiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AkiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "akiservice.AkiService",
	HandlerType: (*AkiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSession",
			Handler:    _AkiService_OpenSession_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _AkiService_CloseSession_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _AkiService_Ping_Handler,
		},
		{
			MethodName: "Hubs",
			Handler:    _AkiService_Hubs_Handler,
		},
		{
			MethodName: "Anisette",
			Handler:    _AkiService_Anisette_Handler,
		},
		{
			MethodName: "AnisetteProvisionStart",
			Handler:    _AkiService_AnisetteProvisionStart_Handler,
		},
		{
			MethodName: "AnisetteProvisionEnd",
			Handler:    _AkiService_AnisetteProvisionEnd_Handler,
		},
		{
			MethodName: "AnisetteIsProvisioned",
			Handler:    _AkiService_AnisetteIsProvisioned_Handler,
		},
		{
			MethodName: "AnisetteProvisionErase",
			Handler:    _AkiService_AnisetteProvisionErase_Handler,
		},
		{
			MethodName: "SetRoutingInfo",
			Handler:    _AkiService_SetRoutingInfo_Handler,
		},
		{
			MethodName: "GetRoutingInfo",
			Handler:    _AkiService_GetRoutingInfo_Handler,
		},
		{
			MethodName: "AnisetteSynchronize",
			Handler:    _AkiService_AnisetteSynchronize_Handler,
		},
		{
			MethodName: "LoginCode",
			Handler:    _AkiService_LoginCode_Handler,
		},
		{
			MethodName: "SAPExchange",
			Handler:    _AkiService_SAPExchange_Handler,
		},
		{
			MethodName: "SAPSign",
			Handler:    _AkiService_SAPSign_Handler,
		},
		{
			MethodName: "SAPPrimeSign",
			Handler:    _AkiService_SAPPrimeSign_Handler,
		},
		{
			MethodName: "SAPVerify",
			Handler:    _AkiService_SAPVerify_Handler,
		},
		{
			MethodName: "SAPPrimeVerify",
			Handler:    _AkiService_SAPPrimeVerify_Handler,
		},
		{
			MethodName: "CloseSAPContext",
			Handler:    _AkiService_CloseSAPContext_Handler,
		},
		{
			MethodName: "SSVGetFairPlayContext",
			Handler:    _AkiService_SSVGetFairPlayContext_Handler,
		},
		{
			MethodName: "SSVIsValidContext",
			Handler:    _AkiService_SSVIsValidContext_Handler,
		},
		{
			MethodName: "SSVSubscriptionBag",
			Handler:    _AkiService_SSVSubscriptionBag_Handler,
		},
		{
			MethodName: "SSVSubscriptionRequest",
			Handler:    _AkiService_SSVSubscriptionRequest_Handler,
		},
		{
			MethodName: "SSVImportKeybag",
			Handler:    _AkiService_SSVImportKeybag_Handler,
		},
		{
			MethodName: "SSVImportSubKeybag",
			Handler:    _AkiService_SSVImportSubKeybag_Handler,
		},
		{
			MethodName: "SSVImportSubResponse",
			Handler:    _AkiService_SSVImportSubResponse_Handler,
		},
		{
			MethodName: "SSVStopSubscriptionLease",
			Handler:    _AkiService_SSVStopSubscriptionLease_Handler,
		},
		{
			MethodName: "SSVDestroyFairPlayContext",
			Handler:    _AkiService_SSVDestroyFairPlayContext_Handler,
		},
		{
			MethodName: "SSVKeyBagSyncData",
			Handler:    _AkiService_SSVKeyBagSyncData_Handler,
		},
		{
			MethodName: "QuickSign",
			Handler:    _AkiService_QuickSign_Handler,
		},
		{
			MethodName: "RSASign",
			Handler:    _AkiService_RSASign_Handler,
		},
		{
			MethodName: "NACExchange1",
			Handler:    _AkiService_NACExchange1_Handler,
		},
		{
			MethodName: "NACExchange2",
			Handler:    _AkiService_NACExchange2_Handler,
		},
		{
			MethodName: "NACSign",
			Handler:    _AkiService_NACSign_Handler,
		},
		{
			MethodName: "CloseNACContext",
			Handler:    _AkiService_CloseNACContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aki.proto",
}
