// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: aki.proto

package akikit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AkiService_OpenSession_FullMethodName                   = "/akiservice.AkiService/OpenSession"
	AkiService_CloseSession_FullMethodName                  = "/akiservice.AkiService/CloseSession"
	AkiService_Ping_FullMethodName                          = "/akiservice.AkiService/Ping"
	AkiService_Hubs_FullMethodName                          = "/akiservice.AkiService/Hubs"
	AkiService_RequestOTPForDSID_FullMethodName             = "/akiservice.AkiService/RequestOTPForDSID"
	AkiService_ProvisionStart_FullMethodName                = "/akiservice.AkiService/ProvisionStart"
	AkiService_ProvisionEnd_FullMethodName                  = "/akiservice.AkiService/ProvisionEnd"
	AkiService_IsProvisioned_FullMethodName                 = "/akiservice.AkiService/IsProvisioned"
	AkiService_ProvisionErase_FullMethodName                = "/akiservice.AkiService/ProvisionErase"
	AkiService_Synchronize_FullMethodName                   = "/akiservice.AkiService/Synchronize"
	AkiService_ProvisionDestroy_FullMethodName              = "/akiservice.AkiService/ProvisionDestroy"
	AkiService_SetRoutingInfo_FullMethodName                = "/akiservice.AkiService/SetRoutingInfo"
	AkiService_GetRoutingInfo_FullMethodName                = "/akiservice.AkiService/GetRoutingInfo"
	AkiService_LoginCode_FullMethodName                     = "/akiservice.AkiService/LoginCode"
	AkiService_SAPExchange_FullMethodName                   = "/akiservice.AkiService/SAPExchange"
	AkiService_SAPSign_FullMethodName                       = "/akiservice.AkiService/SAPSign"
	AkiService_SAPPrimeSign_FullMethodName                  = "/akiservice.AkiService/SAPPrimeSign"
	AkiService_SAPVerify_FullMethodName                     = "/akiservice.AkiService/SAPVerify"
	AkiService_SAPPrimeVerify_FullMethodName                = "/akiservice.AkiService/SAPPrimeVerify"
	AkiService_SAPTeardown_FullMethodName                   = "/akiservice.AkiService/SAPTeardown"
	AkiService_SSVGetFairPlayContext_FullMethodName         = "/akiservice.AkiService/SSVGetFairPlayContext"
	AkiService_SSVIsValidContext_FullMethodName             = "/akiservice.AkiService/SSVIsValidContext"
	AkiService_SSVSubscriptionBag_FullMethodName            = "/akiservice.AkiService/SSVSubscriptionBag"
	AkiService_SSVSubscriptionRequest_FullMethodName        = "/akiservice.AkiService/SSVSubscriptionRequest"
	AkiService_SSVImportKeybag_FullMethodName               = "/akiservice.AkiService/SSVImportKeybag"
	AkiService_SSVImportSubscriptionKeybag_FullMethodName   = "/akiservice.AkiService/SSVImportSubscriptionKeybag"
	AkiService_SSVImportSubscriptionResponse_FullMethodName = "/akiservice.AkiService/SSVImportSubscriptionResponse"
	AkiService_SSVStopSubscriptionLease_FullMethodName      = "/akiservice.AkiService/SSVStopSubscriptionLease"
	AkiService_SSVFairplayDestroy_FullMethodName            = "/akiservice.AkiService/SSVFairplayDestroy"
	AkiService_KeyBagData_FullMethodName                    = "/akiservice.AkiService/KeyBagData"
	AkiService_QuickSign_FullMethodName                     = "/akiservice.AkiService/QuickSign"
	AkiService_RSASign_FullMethodName                       = "/akiservice.AkiService/RSASign"
	AkiService_AbsinExchange1_FullMethodName                = "/akiservice.AkiService/AbsinExchange1"
	AkiService_AbsinExchange2_FullMethodName                = "/akiservice.AkiService/AbsinExchange2"
	AkiService_AbsinSign_FullMethodName                     = "/akiservice.AkiService/AbsinSign"
	AkiService_AbsinTeardown_FullMethodName                 = "/akiservice.AkiService/AbsinTeardown"
)

// AkiServiceClient is the client API for AkiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AkiServiceClient interface {
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*Session, error)
	CloseSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Empty, error)
	Ping(ctx context.Context, in *Session, opts ...grpc.CallOption) (*PingReply, error)
	Hubs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HubsReply, error)
	RequestOTPForDSID(ctx context.Context, in *MachineRequest, opts ...grpc.CallOption) (*OtpReply, error)
	ProvisionStart(ctx context.Context, in *ProvisionStartRequest, opts ...grpc.CallOption) (*ProvisionStartReply, error)
	ProvisionEnd(ctx context.Context, in *ProvisionEndRequest, opts ...grpc.CallOption) (*ProvisionEndReply, error)
	IsProvisioned(ctx context.Context, in *MachineRequest, opts ...grpc.CallOption) (*StatusReply, error)
	ProvisionErase(ctx context.Context, in *MachineRequest, opts ...grpc.CallOption) (*StatusReply, error)
	Synchronize(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeReply, error)
	ProvisionDestroy(ctx context.Context, in *ProvisionDestroyRequest, opts ...grpc.CallOption) (*StatusReply, error)
	SetRoutingInfo(ctx context.Context, in *SetRoutingInfoRequest, opts ...grpc.CallOption) (*ProvisionEndReply, error)
	GetRoutingInfo(ctx context.Context, in *GetRoutingInfoRequest, opts ...grpc.CallOption) (*GetRoutingInfoReply, error)
	LoginCode(ctx context.Context, in *LoginCodeRequest, opts ...grpc.CallOption) (*LoginCodeReply, error)
	SAPExchange(ctx context.Context, in *SAPExchangeRequest, opts ...grpc.CallOption) (*SAPExchangeReply, error)
	SAPSign(ctx context.Context, in *SAPSignRequest, opts ...grpc.CallOption) (*SAPSignReply, error)
	SAPPrimeSign(ctx context.Context, in *SAPSignRequest, opts ...grpc.CallOption) (*SAPSignReply, error)
	SAPVerify(ctx context.Context, in *SAPVerifyRequest, opts ...grpc.CallOption) (*SAPVerifyReply, error)
	SAPPrimeVerify(ctx context.Context, in *SAPVerifyRequest, opts ...grpc.CallOption) (*SAPVerifyReply, error)
	SAPTeardown(ctx context.Context, in *CtxHandle, opts ...grpc.CallOption) (*Empty, error)
	SSVGetFairPlayContext(ctx context.Context, in *SSVGetContextRequest, opts ...grpc.CallOption) (*SSVGetContextReply, error)
	SSVIsValidContext(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*SSVIsValidContextReply, error)
	SSVSubscriptionBag(ctx context.Context, in *SSVSubBagRequest, opts ...grpc.CallOption) (*SSVSubBagReply, error)
	SSVSubscriptionRequest(ctx context.Context, in *SSVSubscriptionRequestRequest, opts ...grpc.CallOption) (*SSVSubscriptionRequestReply, error)
	SSVImportKeybag(ctx context.Context, in *SSVImportRequest, opts ...grpc.CallOption) (*SSVImportReply, error)
	SSVImportSubscriptionKeybag(ctx context.Context, in *SSVImportRequest, opts ...grpc.CallOption) (*SSVImportReply, error)
	SSVImportSubscriptionResponse(ctx context.Context, in *SSVImportSubResponseRequest, opts ...grpc.CallOption) (*SSVImportReply, error)
	SSVStopSubscriptionLease(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*Empty, error)
	SSVFairplayDestroy(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*Empty, error)
	KeyBagData(ctx context.Context, in *KeyBagDataRequest, opts ...grpc.CallOption) (*KeyBagDataReply, error)
	QuickSign(ctx context.Context, in *QuickSignRequest, opts ...grpc.CallOption) (*QuickSignReply, error)
	RSASign(ctx context.Context, in *RSASignRequest, opts ...grpc.CallOption) (*RSASignReply, error)
	AbsinExchange1(ctx context.Context, in *AbsinExchange1Request, opts ...grpc.CallOption) (*AbsinExchange1Reply, error)
	AbsinExchange2(ctx context.Context, in *AbsinExchange2Request, opts ...grpc.CallOption) (*Empty, error)
	AbsinSign(ctx context.Context, in *AbsinSignRequest, opts ...grpc.CallOption) (*AbsinSignReply, error)
	AbsinTeardown(ctx context.Context, in *CtxHandle, opts ...grpc.CallOption) (*Empty, error)
}

type akiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAkiServiceClient(cc grpc.ClientConnInterface) AkiServiceClient {
	return &akiServiceClient{cc}
}

func (c *akiServiceClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, AkiService_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) CloseSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) Ping(ctx context.Context, in *Session, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, AkiService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) Hubs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HubsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HubsReply)
	err := c.cc.Invoke(ctx, AkiService_Hubs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) RequestOTPForDSID(ctx context.Context, in *MachineRequest, opts ...grpc.CallOption) (*OtpReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OtpReply)
	err := c.cc.Invoke(ctx, AkiService_RequestOTPForDSID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) ProvisionStart(ctx context.Context, in *ProvisionStartRequest, opts ...grpc.CallOption) (*ProvisionStartReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionStartReply)
	err := c.cc.Invoke(ctx, AkiService_ProvisionStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) ProvisionEnd(ctx context.Context, in *ProvisionEndRequest, opts ...grpc.CallOption) (*ProvisionEndReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionEndReply)
	err := c.cc.Invoke(ctx, AkiService_ProvisionEnd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) IsProvisioned(ctx context.Context, in *MachineRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, AkiService_IsProvisioned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) ProvisionErase(ctx context.Context, in *MachineRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, AkiService_ProvisionErase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) Synchronize(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynchronizeReply)
	err := c.cc.Invoke(ctx, AkiService_Synchronize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) ProvisionDestroy(ctx context.Context, in *ProvisionDestroyRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, AkiService_ProvisionDestroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SetRoutingInfo(ctx context.Context, in *SetRoutingInfoRequest, opts ...grpc.CallOption) (*ProvisionEndReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionEndReply)
	err := c.cc.Invoke(ctx, AkiService_SetRoutingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) GetRoutingInfo(ctx context.Context, in *GetRoutingInfoRequest, opts ...grpc.CallOption) (*GetRoutingInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingInfoReply)
	err := c.cc.Invoke(ctx, AkiService_GetRoutingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) LoginCode(ctx context.Context, in *LoginCodeRequest, opts ...grpc.CallOption) (*LoginCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginCodeReply)
	err := c.cc.Invoke(ctx, AkiService_LoginCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SAPExchange(ctx context.Context, in *SAPExchangeRequest, opts ...grpc.CallOption) (*SAPExchangeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SAPExchangeReply)
	err := c.cc.Invoke(ctx, AkiService_SAPExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SAPSign(ctx context.Context, in *SAPSignRequest, opts ...grpc.CallOption) (*SAPSignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SAPSignReply)
	err := c.cc.Invoke(ctx, AkiService_SAPSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SAPPrimeSign(ctx context.Context, in *SAPSignRequest, opts ...grpc.CallOption) (*SAPSignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SAPSignReply)
	err := c.cc.Invoke(ctx, AkiService_SAPPrimeSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SAPVerify(ctx context.Context, in *SAPVerifyRequest, opts ...grpc.CallOption) (*SAPVerifyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SAPVerifyReply)
	err := c.cc.Invoke(ctx, AkiService_SAPVerify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SAPPrimeVerify(ctx context.Context, in *SAPVerifyRequest, opts ...grpc.CallOption) (*SAPVerifyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SAPVerifyReply)
	err := c.cc.Invoke(ctx, AkiService_SAPPrimeVerify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SAPTeardown(ctx context.Context, in *CtxHandle, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_SAPTeardown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVGetFairPlayContext(ctx context.Context, in *SSVGetContextRequest, opts ...grpc.CallOption) (*SSVGetContextReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVGetContextReply)
	err := c.cc.Invoke(ctx, AkiService_SSVGetFairPlayContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVIsValidContext(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*SSVIsValidContextReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVIsValidContextReply)
	err := c.cc.Invoke(ctx, AkiService_SSVIsValidContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVSubscriptionBag(ctx context.Context, in *SSVSubBagRequest, opts ...grpc.CallOption) (*SSVSubBagReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVSubBagReply)
	err := c.cc.Invoke(ctx, AkiService_SSVSubscriptionBag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVSubscriptionRequest(ctx context.Context, in *SSVSubscriptionRequestRequest, opts ...grpc.CallOption) (*SSVSubscriptionRequestReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVSubscriptionRequestReply)
	err := c.cc.Invoke(ctx, AkiService_SSVSubscriptionRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVImportKeybag(ctx context.Context, in *SSVImportRequest, opts ...grpc.CallOption) (*SSVImportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVImportReply)
	err := c.cc.Invoke(ctx, AkiService_SSVImportKeybag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVImportSubscriptionKeybag(ctx context.Context, in *SSVImportRequest, opts ...grpc.CallOption) (*SSVImportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVImportReply)
	err := c.cc.Invoke(ctx, AkiService_SSVImportSubscriptionKeybag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVImportSubscriptionResponse(ctx context.Context, in *SSVImportSubResponseRequest, opts ...grpc.CallOption) (*SSVImportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSVImportReply)
	err := c.cc.Invoke(ctx, AkiService_SSVImportSubscriptionResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVStopSubscriptionLease(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_SSVStopSubscriptionLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) SSVFairplayDestroy(ctx context.Context, in *SSVContextHandle, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_SSVFairplayDestroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) KeyBagData(ctx context.Context, in *KeyBagDataRequest, opts ...grpc.CallOption) (*KeyBagDataReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyBagDataReply)
	err := c.cc.Invoke(ctx, AkiService_KeyBagData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) QuickSign(ctx context.Context, in *QuickSignRequest, opts ...grpc.CallOption) (*QuickSignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuickSignReply)
	err := c.cc.Invoke(ctx, AkiService_QuickSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) RSASign(ctx context.Context, in *RSASignRequest, opts ...grpc.CallOption) (*RSASignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RSASignReply)
	err := c.cc.Invoke(ctx, AkiService_RSASign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) AbsinExchange1(ctx context.Context, in *AbsinExchange1Request, opts ...grpc.CallOption) (*AbsinExchange1Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbsinExchange1Reply)
	err := c.cc.Invoke(ctx, AkiService_AbsinExchange1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) AbsinExchange2(ctx context.Context, in *AbsinExchange2Request, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_AbsinExchange2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) AbsinSign(ctx context.Context, in *AbsinSignRequest, opts ...grpc.CallOption) (*AbsinSignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbsinSignReply)
	err := c.cc.Invoke(ctx, AkiService_AbsinSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akiServiceClient) AbsinTeardown(ctx context.Context, in *CtxHandle, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AkiService_AbsinTeardown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AkiServiceServer is the server API for AkiService service.
// All implementations must embed UnimplementedAkiServiceServer
// for forward compatibility.
type AkiServiceServer interface {
	OpenSession(context.Context, *OpenSessionRequest) (*Session, error)
	CloseSession(context.Context, *Session) (*Empty, error)
	Ping(context.Context, *Session) (*PingReply, error)
	Hubs(context.Context, *Empty) (*HubsReply, error)
	RequestOTPForDSID(context.Context, *MachineRequest) (*OtpReply, error)
	ProvisionStart(context.Context, *ProvisionStartRequest) (*ProvisionStartReply, error)
	ProvisionEnd(context.Context, *ProvisionEndRequest) (*ProvisionEndReply, error)
	IsProvisioned(context.Context, *MachineRequest) (*StatusReply, error)
	ProvisionErase(context.Context, *MachineRequest) (*StatusReply, error)
	Synchronize(context.Context, *SynchronizeRequest) (*SynchronizeReply, error)
	ProvisionDestroy(context.Context, *ProvisionDestroyRequest) (*StatusReply, error)
	SetRoutingInfo(context.Context, *SetRoutingInfoRequest) (*ProvisionEndReply, error)
	GetRoutingInfo(context.Context, *GetRoutingInfoRequest) (*GetRoutingInfoReply, error)
	LoginCode(context.Context, *LoginCodeRequest) (*LoginCodeReply, error)
	SAPExchange(context.Context, *SAPExchangeRequest) (*SAPExchangeReply, error)
	SAPSign(context.Context, *SAPSignRequest) (*SAPSignReply, error)
	SAPPrimeSign(context.Context, *SAPSignRequest) (*SAPSignReply, error)
	SAPVerify(context.Context, *SAPVerifyRequest) (*SAPVerifyReply, error)
	SAPPrimeVerify(context.Context, *SAPVerifyRequest) (*SAPVerifyReply, error)
	SAPTeardown(context.Context, *CtxHandle) (*Empty, error)
	SSVGetFairPlayContext(context.Context, *SSVGetContextRequest) (*SSVGetContextReply, error)
	SSVIsValidContext(context.Context, *SSVContextHandle) (*SSVIsValidContextReply, error)
	SSVSubscriptionBag(context.Context, *SSVSubBagRequest) (*SSVSubBagReply, error)
	SSVSubscriptionRequest(context.Context, *SSVSubscriptionRequestRequest) (*SSVSubscriptionRequestReply, error)
	SSVImportKeybag(context.Context, *SSVImportRequest) (*SSVImportReply, error)
	SSVImportSubscriptionKeybag(context.Context, *SSVImportRequest) (*SSVImportReply, error)
	SSVImportSubscriptionResponse(context.Context, *SSVImportSubResponseRequest) (*SSVImportReply, error)
	SSVStopSubscriptionLease(context.Context, *SSVContextHandle) (*Empty, error)
	SSVFairplayDestroy(context.Context, *SSVContextHandle) (*Empty, error)
	KeyBagData(context.Context, *KeyBagDataRequest) (*KeyBagDataReply, error)
	QuickSign(context.Context, *QuickSignRequest) (*QuickSignReply, error)
	RSASign(context.Context, *RSASignRequest) (*RSASignReply, error)
	AbsinExchange1(context.Context, *AbsinExchange1Request) (*AbsinExchange1Reply, error)
	AbsinExchange2(context.Context, *AbsinExchange2Request) (*Empty, error)
	AbsinSign(context.Context, *AbsinSignRequest) (*AbsinSignReply, error)
	AbsinTeardown(context.Context, *CtxHandle) (*Empty, error)
	mustEmbedUnimplementedAkiServiceServer()
}

// UnimplementedAkiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAkiServiceServer struct{}

func (UnimplementedAkiServiceServer) OpenSession(context.Context, *OpenSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedAkiServiceServer) CloseSession(context.Context, *Session) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedAkiServiceServer) Ping(context.Context, *Session) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAkiServiceServer) Hubs(context.Context, *Empty) (*HubsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hubs not implemented")
}
func (UnimplementedAkiServiceServer) RequestOTPForDSID(context.Context, *MachineRequest) (*OtpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestOTPForDSID not implemented")
}
func (UnimplementedAkiServiceServer) ProvisionStart(context.Context, *ProvisionStartRequest) (*ProvisionStartReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionStart not implemented")
}
func (UnimplementedAkiServiceServer) ProvisionEnd(context.Context, *ProvisionEndRequest) (*ProvisionEndReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionEnd not implemented")
}
func (UnimplementedAkiServiceServer) IsProvisioned(context.Context, *MachineRequest) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsProvisioned not implemented")
}
func (UnimplementedAkiServiceServer) ProvisionErase(context.Context, *MachineRequest) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionErase not implemented")
}
func (UnimplementedAkiServiceServer) Synchronize(context.Context, *SynchronizeRequest) (*SynchronizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Synchronize not implemented")
}
func (UnimplementedAkiServiceServer) ProvisionDestroy(context.Context, *ProvisionDestroyRequest) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionDestroy not implemented")
}
func (UnimplementedAkiServiceServer) SetRoutingInfo(context.Context, *SetRoutingInfoRequest) (*ProvisionEndReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRoutingInfo not implemented")
}
func (UnimplementedAkiServiceServer) GetRoutingInfo(context.Context, *GetRoutingInfoRequest) (*GetRoutingInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingInfo not implemented")
}
func (UnimplementedAkiServiceServer) LoginCode(context.Context, *LoginCodeRequest) (*LoginCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginCode not implemented")
}
func (UnimplementedAkiServiceServer) SAPExchange(context.Context, *SAPExchangeRequest) (*SAPExchangeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAPExchange not implemented")
}
func (UnimplementedAkiServiceServer) SAPSign(context.Context, *SAPSignRequest) (*SAPSignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAPSign not implemented")
}
func (UnimplementedAkiServiceServer) SAPPrimeSign(context.Context, *SAPSignRequest) (*SAPSignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAPPrimeSign not implemented")
}
func (UnimplementedAkiServiceServer) SAPVerify(context.Context, *SAPVerifyRequest) (*SAPVerifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAPVerify not implemented")
}
func (UnimplementedAkiServiceServer) SAPPrimeVerify(context.Context, *SAPVerifyRequest) (*SAPVerifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAPPrimeVerify not implemented")
}
func (UnimplementedAkiServiceServer) SAPTeardown(context.Context, *CtxHandle) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAPTeardown not implemented")
}
func (UnimplementedAkiServiceServer) SSVGetFairPlayContext(context.Context, *SSVGetContextRequest) (*SSVGetContextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVGetFairPlayContext not implemented")
}
func (UnimplementedAkiServiceServer) SSVIsValidContext(context.Context, *SSVContextHandle) (*SSVIsValidContextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVIsValidContext not implemented")
}
func (UnimplementedAkiServiceServer) SSVSubscriptionBag(context.Context, *SSVSubBagRequest) (*SSVSubBagReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVSubscriptionBag not implemented")
}
func (UnimplementedAkiServiceServer) SSVSubscriptionRequest(context.Context, *SSVSubscriptionRequestRequest) (*SSVSubscriptionRequestReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVSubscriptionRequest not implemented")
}
func (UnimplementedAkiServiceServer) SSVImportKeybag(context.Context, *SSVImportRequest) (*SSVImportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVImportKeybag not implemented")
}
func (UnimplementedAkiServiceServer) SSVImportSubscriptionKeybag(context.Context, *SSVImportRequest) (*SSVImportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVImportSubscriptionKeybag not implemented")
}
func (UnimplementedAkiServiceServer) SSVImportSubscriptionResponse(context.Context, *SSVImportSubResponseRequest) (*SSVImportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVImportSubscriptionResponse not implemented")
}
func (UnimplementedAkiServiceServer) SSVStopSubscriptionLease(context.Context, *SSVContextHandle) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVStopSubscriptionLease not implemented")
}
func (UnimplementedAkiServiceServer) SSVFairplayDestroy(context.Context, *SSVContextHandle) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSVFairplayDestroy not implemented")
}
func (UnimplementedAkiServiceServer) KeyBagData(context.Context, *KeyBagDataRequest) (*KeyBagDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeyBagData not implemented")
}
func (UnimplementedAkiServiceServer) QuickSign(context.Context, *QuickSignRequest) (*QuickSignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuickSign not implemented")
}
func (UnimplementedAkiServiceServer) RSASign(context.Context, *RSASignRequest) (*RSASignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RSASign not implemented")
}
func (UnimplementedAkiServiceServer) AbsinExchange1(context.Context, *AbsinExchange1Request) (*AbsinExchange1Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbsinExchange1 not implemented")
}
func (UnimplementedAkiServiceServer) AbsinExchange2(context.Context, *AbsinExchange2Request) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbsinExchange2 not implemented")
}
func (UnimplementedAkiServiceServer) AbsinSign(context.Context, *AbsinSignRequest) (*AbsinSignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbsinSign not implemented")
}
func (UnimplementedAkiServiceServer) AbsinTeardown(context.Context, *CtxHandle) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbsinTeardown not implemented")
}
func (UnimplementedAkiServiceServer) mustEmbedUnimplementedAkiServiceServer() {}
func (UnimplementedAkiServiceServer) testEmbeddedByValue()                    {}

// UnsafeAkiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AkiServiceServer will
// result in compilation errors.
type UnsafeAkiServiceServer interface {
	mustEmbedUnimplementedAkiServiceServer()
}

func RegisterAkiServiceServer(s grpc.ServiceRegistrar, srv AkiServiceServer) {
	// If the following call pancis, it indicates UnimplementedAkiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AkiService_ServiceDesc, srv)
}

func _AkiService_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).CloseSession(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).Ping(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_Hubs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).Hubs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_Hubs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).Hubs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_RequestOTPForDSID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).RequestOTPForDSID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_RequestOTPForDSID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).RequestOTPForDSID(ctx, req.(*MachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_ProvisionStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).ProvisionStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_ProvisionStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).ProvisionStart(ctx, req.(*ProvisionStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_ProvisionEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionEndRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).ProvisionEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_ProvisionEnd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).ProvisionEnd(ctx, req.(*ProvisionEndRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_IsProvisioned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).IsProvisioned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_IsProvisioned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).IsProvisioned(ctx, req.(*MachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_ProvisionErase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).ProvisionErase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_ProvisionErase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).ProvisionErase(ctx, req.(*MachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_Synchronize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynchronizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).Synchronize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_Synchronize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).Synchronize(ctx, req.(*SynchronizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_ProvisionDestroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).ProvisionDestroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_ProvisionDestroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).ProvisionDestroy(ctx, req.(*ProvisionDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SetRoutingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoutingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SetRoutingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SetRoutingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SetRoutingInfo(ctx, req.(*SetRoutingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_GetRoutingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).GetRoutingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_GetRoutingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).GetRoutingInfo(ctx, req.(*GetRoutingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_LoginCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).LoginCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_LoginCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).LoginCode(ctx, req.(*LoginCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SAPExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAPExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SAPExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SAPExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SAPExchange(ctx, req.(*SAPExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SAPSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAPSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SAPSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SAPSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SAPSign(ctx, req.(*SAPSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SAPPrimeSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAPSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SAPPrimeSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SAPPrimeSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SAPPrimeSign(ctx, req.(*SAPSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SAPVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAPVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SAPVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SAPVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SAPVerify(ctx, req.(*SAPVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SAPPrimeVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAPVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SAPPrimeVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SAPPrimeVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SAPPrimeVerify(ctx, req.(*SAPVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SAPTeardown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtxHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SAPTeardown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SAPTeardown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SAPTeardown(ctx, req.(*CtxHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVGetFairPlayContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVGetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVGetFairPlayContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVGetFairPlayContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVGetFairPlayContext(ctx, req.(*SSVGetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVIsValidContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVContextHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVIsValidContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVIsValidContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVIsValidContext(ctx, req.(*SSVContextHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVSubscriptionBag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVSubBagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVSubscriptionBag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVSubscriptionBag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVSubscriptionBag(ctx, req.(*SSVSubBagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVSubscriptionRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVSubscriptionRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVSubscriptionRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVSubscriptionRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVSubscriptionRequest(ctx, req.(*SSVSubscriptionRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVImportKeybag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVImportKeybag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVImportKeybag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVImportKeybag(ctx, req.(*SSVImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVImportSubscriptionKeybag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVImportSubscriptionKeybag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVImportSubscriptionKeybag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVImportSubscriptionKeybag(ctx, req.(*SSVImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVImportSubscriptionResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVImportSubResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVImportSubscriptionResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVImportSubscriptionResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVImportSubscriptionResponse(ctx, req.(*SSVImportSubResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVStopSubscriptionLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVContextHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVStopSubscriptionLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVStopSubscriptionLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVStopSubscriptionLease(ctx, req.(*SSVContextHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_SSVFairplayDestroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSVContextHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).SSVFairplayDestroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_SSVFairplayDestroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).SSVFairplayDestroy(ctx, req.(*SSVContextHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_KeyBagData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyBagDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).KeyBagData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_KeyBagData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).KeyBagData(ctx, req.(*KeyBagDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_QuickSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuickSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).QuickSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_QuickSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).QuickSign(ctx, req.(*QuickSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_RSASign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSASignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).RSASign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_RSASign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).RSASign(ctx, req.(*RSASignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_AbsinExchange1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbsinExchange1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).AbsinExchange1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_AbsinExchange1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).AbsinExchange1(ctx, req.(*AbsinExchange1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_AbsinExchange2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbsinExchange2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).AbsinExchange2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_AbsinExchange2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).AbsinExchange2(ctx, req.(*AbsinExchange2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_AbsinSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbsinSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).AbsinSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_AbsinSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).AbsinSign(ctx, req.(*AbsinSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkiService_AbsinTeardown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtxHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkiServiceServer).AbsinTeardown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkiService_AbsinTeardown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkiServiceServer).AbsinTeardown(ctx, req.(*CtxHandle))
	}
	return interceptor(ctx, in, info, handler)
}

// AkiService_ServiceDesc is the grpc.ServiceDesc for AkiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AkiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "akiservice.AkiService",
	HandlerType: (*AkiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSession",
			Handler:    _AkiService_OpenSession_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _AkiService_CloseSession_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _AkiService_Ping_Handler,
		},
		{
			MethodName: "Hubs",
			Handler:    _AkiService_Hubs_Handler,
		},
		{
			MethodName: "RequestOTPForDSID",
			Handler:    _AkiService_RequestOTPForDSID_Handler,
		},
		{
			MethodName: "ProvisionStart",
			Handler:    _AkiService_ProvisionStart_Handler,
		},
		{
			MethodName: "ProvisionEnd",
			Handler:    _AkiService_ProvisionEnd_Handler,
		},
		{
			MethodName: "IsProvisioned",
			Handler:    _AkiService_IsProvisioned_Handler,
		},
		{
			MethodName: "ProvisionErase",
			Handler:    _AkiService_ProvisionErase_Handler,
		},
		{
			MethodName: "Synchronize",
			Handler:    _AkiService_Synchronize_Handler,
		},
		{
			MethodName: "ProvisionDestroy",
			Handler:    _AkiService_ProvisionDestroy_Handler,
		},
		{
			MethodName: "SetRoutingInfo",
			Handler:    _AkiService_SetRoutingInfo_Handler,
		},
		{
			MethodName: "GetRoutingInfo",
			Handler:    _AkiService_GetRoutingInfo_Handler,
		},
		{
			MethodName: "LoginCode",
			Handler:    _AkiService_LoginCode_Handler,
		},
		{
			MethodName: "SAPExchange",
			Handler:    _AkiService_SAPExchange_Handler,
		},
		{
			MethodName: "SAPSign",
			Handler:    _AkiService_SAPSign_Handler,
		},
		{
			MethodName: "SAPPrimeSign",
			Handler:    _AkiService_SAPPrimeSign_Handler,
		},
		{
			MethodName: "SAPVerify",
			Handler:    _AkiService_SAPVerify_Handler,
		},
		{
			MethodName: "SAPPrimeVerify",
			Handler:    _AkiService_SAPPrimeVerify_Handler,
		},
		{
			MethodName: "SAPTeardown",
			Handler:    _AkiService_SAPTeardown_Handler,
		},
		{
			MethodName: "SSVGetFairPlayContext",
			Handler:    _AkiService_SSVGetFairPlayContext_Handler,
		},
		{
			MethodName: "SSVIsValidContext",
			Handler:    _AkiService_SSVIsValidContext_Handler,
		},
		{
			MethodName: "SSVSubscriptionBag",
			Handler:    _AkiService_SSVSubscriptionBag_Handler,
		},
		{
			MethodName: "SSVSubscriptionRequest",
			Handler:    _AkiService_SSVSubscriptionRequest_Handler,
		},
		{
			MethodName: "SSVImportKeybag",
			Handler:    _AkiService_SSVImportKeybag_Handler,
		},
		{
			MethodName: "SSVImportSubscriptionKeybag",
			Handler:    _AkiService_SSVImportSubscriptionKeybag_Handler,
		},
		{
			MethodName: "SSVImportSubscriptionResponse",
			Handler:    _AkiService_SSVImportSubscriptionResponse_Handler,
		},
		{
			MethodName: "SSVStopSubscriptionLease",
			Handler:    _AkiService_SSVStopSubscriptionLease_Handler,
		},
		{
			MethodName: "SSVFairplayDestroy",
			Handler:    _AkiService_SSVFairplayDestroy_Handler,
		},
		{
			MethodName: "KeyBagData",
			Handler:    _AkiService_KeyBagData_Handler,
		},
		{
			MethodName: "QuickSign",
			Handler:    _AkiService_QuickSign_Handler,
		},
		{
			MethodName: "RSASign",
			Handler:    _AkiService_RSASign_Handler,
		},
		{
			MethodName: "AbsinExchange1",
			Handler:    _AkiService_AbsinExchange1_Handler,
		},
		{
			MethodName: "AbsinExchange2",
			Handler:    _AkiService_AbsinExchange2_Handler,
		},
		{
			MethodName: "AbsinSign",
			Handler:    _AkiService_AbsinSign_Handler,
		},
		{
			MethodName: "AbsinTeardown",
			Handler:    _AkiService_AbsinTeardown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aki.proto",
}
